version: '3.4'

services:
  dockerexpress:
    image: dockerexpress
    build:
      context: twipoke
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
